# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Security Assessment?!
tagline:             이번 생은 이미 늦은건가..
description:         matta's notes for security assessment and pentesting
url:                 http://me.matta.kr/writeup
baseurl:             '/writeup'
paginate:            5

# About/contact
author:
  name:              JS Park
  url:               http://me.matta.kr
  email:             js00n.park@gmail.com

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/JisoonPark/writeup
  master:            https://github.com/JisoonPark/writeup/blob/master

category_dir: category/
tag_dir: tag/
